name: Pull and deploy to a cloud

on:
  workflow_dispatch:
    inputs:
      test:
        description: "Manual push"
        required: true
        default: "yes"
        
jobs:
  say_hello:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.test == 'yes' }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Docker BuildX
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build
        id: docker-build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: test-app/app-bryant:latest
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      
          
