name: Pull and deploy to a cloud

on:
  workflow_dispatch:
    inputs:
      test:
        description: "Manual push"
        required: true
        default: "yes"
        
jobs:
  say_hello:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.test == 'yes' }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
