---
###########
# CI ######
###########
name: Continous Integration

# 
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

####################
# Start the job on all push #
###########################
on:
  push:
    branches-ignore:
      - 'master'
      - 'main'
      
##############
# Set the job
##############
jobs:
  build:
    # Name the job
    name: CI
    # Set the agent to run on
    runs-on: ubuntu-latest
    ######################
    # Load all steps #
    ######################
    steps:
      ###################
      # Checkout the code base
      ########################
      - name: Checkout code
        uses: actions/checkout@v2
      
      ####################
      # Setup Docker Build X 
      #######################
      - name: Setup Build X
        uses: docker/setup-buildx-action@v1
        
      ##############################
      # Build the Docker container #
      #############################
      - name: Build Docker container
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: ./actions-a/Dockerfile
          build-args: |
            BUILD_DATE=${{ env.BUILD_DATE }}
            BUILD_REVISION=${{ github.sha }}
            BUILD_VERSION=${{ github.sha }}
          push: false
