---
#############
#############
## CT #######
#############
name: Continuous Testing

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#################################
# Start the job on all push #####
#################################
#
on:
  push:
    branches-ignore:
      - 'master'
      - 'main'
      
##################
# Set the job ####
##################
jobs:
  build: 
    # Name the job
    name: CT
    # Set the agent to run on
    runs-on: ubuntu-latest
    #######################
    # Load all steps ######
    #######################
    steps:
      #####################
      # Checkout code base
      ####################
      - name: Checkout code
        uses: actions/checkout@v2
        
      #####################
      # Run linter against code base #
      #################################
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
